#redis
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      max-idle: 8
      min-idle: 0

       连接超时时间（毫秒）
    timeout: 3000

